apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: cxjuq1gc1-python-gitops
  description: This is GitOps manifest for cxjuq1gc1-python   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: tssc/gitops=cxjuq1gc1-python
    backstage.io/kubernetes-id: cxjuq1gc1-python 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: cxjuq1gc1-python
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:cxjuq1gc1-python
