apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: cxjuq1gc1-python
  janus-idp.io/tekton: cxjuq1gc1-python
  backstage.io/kubernetes-id: cxjuq1gc1-python
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: cxjuq1gc1-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
